name: Continuous Delivery
on: 
  push:
    branches:
      - main
      
jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
            name: projetozipado
            path: |
                **.py
                README.md
                requirements.txt


  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - name: Download artifact from previous job
        uses: actions/download-artifact@v4
        with:
          name: projetozipado

      - name: Display structure of the downloaded files
        run: ls -R