name: Continuous Delivery
on: 
  push:
    branches:
      - main
      
jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Checar código do repositório
        uses: actions/checkout@v4

      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
            name: projetozipado.zip
            path: |
                '**.py'
                README.md
                requirements.txt
