name: Discord
on:
  - push

jobs:
  discord:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Run Discord Webhook Action!
          uses: Sniddl/discord-commits@v1.6
          with:
            webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
            template: "avatar-with-link"
            inclue-extras: true